name: Build

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'maps.csv'
    branches:
      - master
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'maps.csv'

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
          dotnet-quality: 'ga'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release

      - name: Prepare artifacts
        run: |
          robocopy MapDownloader\bin\Release\net7.0-windows\win-x64\publish\ artifacts MapDownloader.exe /r:0 /w:0
          if ($LastExitCode -le 7) { $LastExitCode = 0 }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: artifacts

  Release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'artifacts/MapDownloader.exe'
          tag: ${{ github.ref }}
